import {
  appCacheDir,
  appConfigDir,
  appDataDir,
  appLocalDataDir,
  appLogDir,
  audioDir,
  BaseDirectory,
  basename,
  cacheDir,
  configDir,
  dataDir,
  delimiter,
  desktopDir,
  dirname,
  documentDir,
  downloadDir,
  executableDir,
  extname,
  fontDir,
  homeDir,
  isAbsolute,
  join,
  localDataDir,
  normalize,
  pictureDir,
  publicDir,
  resolve,
  resolveResource,
  resourceDir,
  runtimeDir,
  sep,
  tempDir,
  templateDir,
  videoDir
} from '@tauri-apps/api/path'
import type { IPath } from '../client/types'

export function constructPathApi(): Omit<IPath, 'BaseDirectory'> {
  return {
    appCacheDir,
    appConfigDir,
    appDataDir,
    appLocalDataDir,
    appLogDir,
    audioDir,
    basename,
    cacheDir,
    configDir,
    dataDir,
    delimiter: () => Promise.resolve(delimiter()),
    desktopDir,
    dirname,
    documentDir,
    downloadDir,
    executableDir,
    extname,
    fontDir,
    homeDir,
    isAbsolute,
    join,
    localDataDir,
    normalize,
    pictureDir,
    publicDir,
    resolve,
    resolveResource,
    resourceDir,
    runtimeDir,
    sep: () => Promise.resolve(sep()),
    tempDir,
    templateDir,
    videoDir
  }
}
